import logging

DEBUG = True
LOG_LEVEL = logging.DEBUG
LOG_FILE = 'debug.log'
MYSQL_ROOT_USER = 'defaultUser'
MYSQL_ROOT_PASSWORD = 'defaultPassword'
MYSQL_HOST = 'defaultMySQLServer'
MYSQL_DATABASE = 'so_tickets_db'
SQLALCHEMY_DATABASE_URI = f'mysql+mysqlconnector://{MYSQL_ROOT_USER}:{MYSQL_ROOT_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
REDIS_HOST = 'redis'
REDIS_PORT = '6379'
OTP_EXPIRY_SECONDS = 600
SAVE_TICKETS_DURATION_SECONDS = 600
MAX_TICKETS_PER_CLIENT = 10
MAIL_SERVER='smtp.gmail.com'
MAIL_PORT = 465
MAIL_USERNAME = 'user@gmail.com'
MAIL_PASSWORD = 'password'
MAIL_USE_TLS = False
MAIL_USE_SSL = True
JWT_SECRET_KEY = "JWT_SECRET"
JWT_EXPIRATION_MINUTES = 600